// THIS AUTOGENERATED FILE ENABLES ES MODULES IN NODE
// Set options as a parameter, environment variable, or rc file.

require('dotenv').config()
// eslint-disable-next-line no-global-assign
require = require('esm')(module/* , options */)
module.exports = require('./app.js').default
