import { useForm, ErrorMessage } from 'react-hook-form'
import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import { useQuery, useMutation } from '@apollo/client'
import { useToasts } from 'react-toast-notifications'
import gql from 'graphql-tag'
import Link from 'next/link'
import Loader from 'react-loader-spinner'

import { useTheme } from 'context/ColorContext'
import colorConverter from 'lib/colorConverter'
import PleaseSignIn from 'components/PleaseSignIn'
import { ColorRadio } from 'components/EditForum'
